import Trainer1 from "../images/jayprakash";
import Trainer2 from "../images//rajpatwa.webp";
import { imageData } from "../images/img_index";
export const trainerDetail = [
  {
    id: 1,
    name: "Jayprakash Dhakad",
    phoneNumber: "+91 32939384",
    img: Trainer1,
    para1:
      "This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large",
    para2:
      "This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens.",
    specially: "conclusion",
    certification: "certification",
    Experience: "5+, sleft practice",
    flex: 80,
    skill: 70,
    access: 80,
  },
  {
    id: 2,
    name: "Raj Patwa",
    phoneNumber: "+91 32939384",
    img: Trainer2,
    para1:
      "This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large",
    para2:
      "This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens.",
    specially: "conclusion",
    certification: "certification",
    Experience: "4+, sleft practice",
    flex: 85,
    skill: 77,
    access: 90,
  },
  {
    id: 3,
    name: "Rohan Prajapati",
    phoneNumber: "+91 32939384",
    img: "https://img.freepik.com/free-photo/front-view-man-meditating-outdoors_23-2148988371.jpg?t=st=1725514513~exp=1725518113~hmac=e9312fd1e1f17184f41605c522516f8c44437923c1ae5395bc4af2aea4ad6987&w=360",
    para1:
      "This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large",
    para2:
      "This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens. This column takes up 9/12 of the width on extra-large screens.",
    specially: "conclusion",
    certification: "certification",
    Experience: "4+, sleft practice",
    flex: 87,
    skill: 80,
    access: 99,
  },
];


export const eevent = [
  {
    id: "1",
    eventName: "",
    heading:'Classes',
    eventData: [
      {
        id: 1,
        image: imageData.HomeYoga,
        type: "Time Flexibility",
        link: "#",
        date: "14 Feb",
        slug: '/homeclasses',
        title: "Home/Personal Yoga Classes",
        duration: "50 min / Session",
        registrationDate: "08-11-2023",
        price: "$240 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 2,
        image: imageData.CommunityYoga,
        type: "Empower Communities",
        link: "event-style-1.html",
        date: "14 Feb",
        title: "Society Yoga Classes",
        slug: '/societyclasses',
        duration: "55 min / Session",
        registrationDate: "22-11-2023",
        price: "$300 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 3,
        image: imageData.CorporateYoga,
        type: "Stress Buster",
        link: "event-style-1.html",
        date: "14 Feb",
        title: "Corporate Yoga",
        slug: '/corporateclasses',
        duration: "60 min / Session",
        registrationDate: "20-11-2023",
        price: "$330 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 4,
        image: imageData.Women_Yoga,
        type: "Women's special yoga",
        link: "event-style-1.html",
        date: "14 Feb",
        title: "Women's Care Yoga Classes",
        slug: '/womensclasses',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 5,
        image: imageData.F_C_Yoga,
        type: "Deepened Connections",
        link: "#",
        date: "14 Feb",
        title: "Family/Couple Yoga Classes",
        slug:'/familyclasses',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 6,
        image: imageData.EmpYoga,
        type: "Corporate Wellbeing System",
        link: "#",
        date: "14 Feb",
        title: "Office Yoga Classes",
        slug: '/officesclasses',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },

      {
        id: 7,
        image: imageData.AbroadYoga,
        type: "Yoga Around The World",
        link: "#",

        date: "14 Feb",
        title: "Yoga for Abroad",
        slug:'/abroadclasses',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },

      {
        id: 8,
        image: imageData.Occupation_Yoga,
        type: "Word related Occasion",
        link: "#",

        date: "14 Feb",
        title: "Occupational Yoga Classes",
        slug:'/occupationclasses',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      
      {
        id: 9,
        image: imageData.Occupation_Yoga,
        type: "Word related Occasion",
        link: "#",

        date: "14 Feb",
        title: "Resort & tourist yoga",
        slug:'/resorttourist',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 10,
        image: imageData.Occupation_Yoga,
        type: "Word related Occasion",
        link: "#",

        date: "14 Feb",
        title: " On-line yoga classes ",
        slug:'/onlinyoga',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
    ],
  },
  {
    id: "2",
    eventName: "",
    heading:'Consultaation',
    eventData: [
      {
        id: 1,
        image:
          "https://img.freepik.com/free-photo/patient-nurse-with-face-masks-looking-spine-bones_482257-27000.jpg?t=st=1724840602~exp=1724844202~hmac=a1deec2183c3c5ee3bd8e4229f57be4d7daef1f59092a3d466f923e99bd29956&w=900",
        type: "Mobility",
        link: "#",
        date: "14 Feb",
        title: "Orthopedic Consultation",
        slug:'/orthopedic',
        slug2:``,
        duration: "50 min / Session",
        registrationDate: "08-11-2023",
        price: "$240 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 2,
        image:
          "https://img.freepik.com/free-photo/happy-doctor-holding-clipboard-with-patients_1098-2176.jpg?t=st=1724840646~exp=1724844246~hmac=170fea2728daa31010a6f445b3cc4f297bfeb9f73832806f3e2b1f6f566fce88&w=900",
        type: "Physical",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Physician Consultation",
        slug:'/physician',
        duration: "55 min / Session",
        registrationDate: "22-11-2023",
        price: "$300 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 3,
        image:
          "https://img.freepik.com/free-photo/mid-shot-woman-therapist-with-clipboard_23-2148759113.jpg?t=st=1724840778~exp=1724844378~hmac=75237c075bc65ebce65419b3efac7a1372cce597e21e626db145f724d18a9cbe&w=740",
        type: "Mental Well-Being",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Corporate Consultation",
        slug:'/corporate',
        duration: "60 min / Session",
        registrationDate: "20-11-2023",
        price: "$330 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 4,
        image:
          "https://img.freepik.com/free-photo/smiling-athletic-woman-is-doing-yoga_8353-10209.jpg?t=st=1724840826~exp=1724844426~hmac=e9169d28058b4f45f300adb27202412d376acc9204e88835d4f17df05b0e248c&w=360",
        type: "Holistic Wellness",
        link: "#",

        date: "14 Feb",
        title: "Yoga Expert Consultation",
        slug:'/yoga-expert',
        duration: "45 min / Session",
        registrationDate: "14-11-2023",
        price: "$200 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 5,
        image:
          "https://img.freepik.com/free-photo/medium-shot-smiley-doctor-talking-woman_23-2149047476.jpg?t=st=1724840919~exp=1724844519~hmac=48133a220115020a6681fa8764a22c01cc40ec7e9d610dc7142ed1c11c29ffce&w=900",
        type: "Inner Fire",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Motivational Consultation",
        slug:'/motivational',
        duration: "55 min / Session",
        registrationDate: "11-11-2023",
        price: "$370 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 6,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Counsellor Consultation",
        slug:'/counsellor',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
    ],
  },
  {
    id: "3",
    eventName: "",
    heading:'yoga_type',
    eventData: [
      {
        id: 1,
        image:
          "https://img.freepik.com/free-photo/patient-nurse-with-face-masks-looking-spine-bones_482257-27000.jpg?t=st=1724840602~exp=1724844202~hmac=a1deec2183c3c5ee3bd8e4229f57be4d7daef1f59092a3d466f923e99bd29956&w=900",
        type: "Mobility",
        link: "#",
        date: "14 Feb",
        title: "Yoga Therapy",
        slug:'/yogathreapy',
        slug2:``,
        duration: "50 min / Session",
        registrationDate: "08-11-2023",
        price: "$240 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 2,
        image:
          "https://img.freepik.com/free-photo/happy-doctor-holding-clipboard-with-patients_1098-2176.jpg?t=st=1724840646~exp=1724844246~hmac=170fea2728daa31010a6f445b3cc4f297bfeb9f73832806f3e2b1f6f566fce88&w=900",
        type: "Physical",
        link: "event-style-1.html",

        date: "14 Feb",
        title: " Vinyasa flow",
        slug:'/vinyasaflow',
        duration: "55 min / Session",
        registrationDate: "22-11-2023",
        price: "$300 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 3,
        image:
          "https://img.freepik.com/free-photo/mid-shot-woman-therapist-with-clipboard_23-2148759113.jpg?t=st=1724840778~exp=1724844378~hmac=75237c075bc65ebce65419b3efac7a1372cce597e21e626db145f724d18a9cbe&w=740",
        type: "Mental Well-Being",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Traditional Yoga",
        slug:'/traditional_yoga',
        duration: "60 min / Session",
        registrationDate: "20-11-2023",
        price: "$330 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 4,
        image:
          "https://img.freepik.com/free-photo/smiling-athletic-woman-is-doing-yoga_8353-10209.jpg?t=st=1724840826~exp=1724844426~hmac=e9169d28058b4f45f300adb27202412d376acc9204e88835d4f17df05b0e248c&w=360",
        type: "Holistic Wellness",
        link: "#",

        date: "14 Feb",
        title: "Ashtanga Yoga",
        slug:'/ashtangayoga ',
        duration: "45 min / Session",
        registrationDate: "14-11-2023",
        price: "$200 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 5,
        image:
          "https://img.freepik.com/free-photo/medium-shot-smiley-doctor-talking-woman_23-2149047476.jpg?t=st=1724840919~exp=1724844519~hmac=48133a220115020a6681fa8764a22c01cc40ec7e9d610dc7142ed1c11c29ffce&w=900",
        type: "Inner Fire",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Hatha yoga ",
        slug:'/hatha_yoga',
        duration: "55 min / Session",
        registrationDate: "11-11-2023",
        price: "$370 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 6,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Power Yoga ",
        slug:'/power_yoga ',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 7,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Raja yoga",
        slug:'/raja_yoga',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 8,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Chair yoga, wheel yoga",
        slug:'/chair_yoga',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 9,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Strap band and blocks yoga",
        slug:'/strap',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 10,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Strap band and blocks yoga",
        slug:'/strap',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 12,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Competitive yogasana",
        slug:'/competitiveyogasana',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 13,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Prana Healing Yoga",
        slug:'/pranahealingyoga',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },
      {
        id: 14,
        image:
          "https://img.freepik.com/free-photo/family-therapy-psychologist-office_23-2149175189.jpg?t=st=1724841231~exp=1724844831~hmac=13c11f84dc82e32abb5c73ccb4084e41f778427d504f607e4ccd3acd2ec605be&w=900",
        type: "Support",
        link: "event-style-1.html",

        date: "14 Feb",
        title: "Prana Healing Yoga",
        slug:'/pranahealingyoga',
        duration: "30 min / Session",
        registrationDate: "01-11-2023",
        price: "$245 / Month",
        descp: `e It’s time to roll out your yoga mat and discovers combinations of physically and mentally exercises be While most people associate yoga with stretching and flexibility, some considered strength-building types of yoga classes can also be. It just depends on the class level, approach, and teacher. This makes yoga asana a multimodal form of exercise`,
        descp2: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of the evidence so far supports what practitioners seem to have known for millennia: Yoga is incredibly beneficial to our overall well-being. Flexibility is an important component of physical health. Yoga offers many styles to choose from, varying in intensity from high to moderate to mild. Even the lowest and intensity styles have been found to increase flexibilitySo, it makes sense that the second most cited reason people selected as to why they do yoga was to relieve stress`,
        descp3: `The scientific research into yoga’s benefits is still somewhat preliminary, but much of`,
      },

    ],
  },
];
